# Generated by Django 4.2.4 on 2023-09-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='bio',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
